csv_parser:
  sample_percentage: 0.2
  max_file_size: 10485760 # 10MB
  supported_encodings: ["utf-8", "latin1", "cp1252"]
  output_format: "json"

llm_settings:
  model: "gpt-4o-mini"
  temperature: 0.1
  max_tokens: 2000
  timeout: 30
  retry_attempts: 3

pattern_recognition:
  confidence_threshold: 0.85
  max_patterns: 10
  validation_sample_size: 50

logging:
  level: "INFO"
  file: "logs/csv_parser.log"
  max_size: "10MB"
  backup_count: 5
